name: mine_detection_app_2
description: A web client for mine detection system

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  dio: ^5.3.2
  web_socket_channel: ^2.4.0
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  json_annotation: ^4.8.1
  intl: ^0.18.1
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true